name: volga_it_hm_2025
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

license: BSD-3-Clause


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^6.1.5
  path_provider: ^2.1.5
  latlong2: ^0.9.1
  flutter_map_marker_cluster: ^1.3.6
  mime: ^2.0.0
  flutter_lints: ^2.0.0
  file_selector: ^1.0.3
  flutter_colorpicker: ^1.1.0
  exif: ^3.3.0
  crop_your_image: ^2.0.0

flutter:
  uses-material-design: true